apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: searchesTeam
spec:
  request: ${searchesTeamCSR}
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth