apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: usermanagement
  name: userManagementTeamRole1
rules:
  - apiGroups: ["*"]
    resources: ["bindings" ]
    verbs: ["create"]