
version: '3'
services:

  mongoDB:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    expose:
      - "27017"
    volumes:
      - dbData:/data/db

  reviews-server:
    container_name: reviews-server
    build: 
      dockerfile: ../reviews/server/Dockerfile
      context: ../reviews


  reviews-api:
    container_name: reviews-api
    build: 
      dockerfile: ../reviews/api/Dockerfile
      context: ../reviews
    environment:
      REVIEWS_SERVER_HOST: reviews-server
    ports:
      - 5012:5012
    expose:
      - "5012"

  adminOperations:
    build:
      dockerfile: ../adminOperations/server/Dockerfile
      context: ../adminOperations
    image: adminoperations
    ports:
      - "50052:50052"

  adminOperations-api:
    build:
      dockerfile: ../adminOperations/api/Dockerfile
      context: ../adminOperations
    environment:
      ADMINOPERATIONS_HOST: adminOperations
    image: apiadminoperations
    ports:
      - "5003:5003"
    expose:
      - "5003"

  usermanagementserver:
    build:
      dockerfile: ../userManagement/server/Dockerfile
      context: ../userManagement
    image: usermanagementserver
    ports:
      - "50054:50054"

  userManagement-api:
    build:
      dockerfile: ../userManagement/api/Dockerfile
      context: ../userManagement
    environment:
      USERMANAGEMENT_HOST: usermanagementserver
    image: apiusermanagement
    ports:
      - "5004:5004"
    expose:
      - "5004"

  libraryserver:
    build:
      dockerfile: ../library/server/Dockerfile
      context: ../library
    image: libraryserver
    ports:
      - "50055:50055"

  library-api:
    build:
      dockerfile: ../library/api/Dockerfile
      context: ../library
    environment:
        LIBRARY_HOST: libraryserver
    image: apilibrary
    ports:
      - "5001:5001"
    expose:
      - "5001"

  wishlist:
    build:
      dockerfile: ../wishlist/server/Dockerfile
      context: ../wishlist
    image: wishlist
    ports:
      - "50058:50058"

  wishlist-api:
    build:
      dockerfile: ../wishlist/api/Dockerfile
      context: ../wishlist
    environment:
      WISHLIST_HOST: wishlist
    image: apiwishlist
    ports:
      - "5002:5002"
    expose:
      - "5002"

  suggestions:
    build:
      dockerfile: ../suggestions/server/Dockerfile
      context: ../suggestions
    image: suggestions
    ports:
      - "50059:50059"

  suggestions-api:
    build:
      dockerfile: ../suggestions/api/Dockerfile
      context: ../suggestions
    environment:
      SUGGESTIONS_HOST: suggestions
    image: apisuggestions
    ports:
      - "5008:5008"
    expose:
      - "5008"

  searchesserver:
    build:
      dockerfile: ../searches/server/Dockerfile
      context: ../searches
    image: searchesserver
    ports:
      - "50060:50060"

  searches-api:
    build:
      dockerfile: ../searches/api/Dockerfile
      context: ../searches
    environment:
      SEARCHES_HOST: searchesserver
    image: searches
    ports:
      - "5010:5010"
    expose:
      - "5010"


volumes:
  dbData:
    external: false
