# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reviews.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import util.util_pb2 as util__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreviews.proto\x1a\nutil.proto\"\xc4\x04\n\x0cReviewObject\x12\x11\n\treview_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61pp_id\x18\x02 \x01(\x05\x12\x10\n\x08\x61pp_name\x18\x03 \x01(\t\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x0e\n\x06review\x18\x05 \x01(\t\x12\x19\n\x11timestamp_created\x18\x06 \x01(\x05\x12\x19\n\x11timestamp_updated\x18\x07 \x01(\x05\x12\x13\n\x0brecommended\x18\x08 \x01(\x08\x12\x15\n\rvotes_helpful\x18\t \x01(\x05\x12\x13\n\x0bvotes_funny\x18\n \x01(\x05\x12\x1b\n\x13weighted_vote_score\x18\x0b \x01(\x05\x12\x15\n\rcomment_count\x18\x0c \x01(\x05\x12\x16\n\x0esteam_purchase\x18\r \x01(\x08\x12\x19\n\x11received_for_free\x18\x0e \x01(\x08\x12#\n\x1bwritten_during_early_access\x18\x0f \x01(\x08\x12\x16\n\x0e\x61uthor_steamid\x18\x10 \x01(\x05\x12\x1e\n\x16\x61uthor_num_games_owned\x18\x11 \x01(\x05\x12\x1a\n\x12\x61uthor_num_reviews\x18\x12 \x01(\x05\x12\x1f\n\x17\x61uthor_playtime_forever\x18\x13 \x01(\x05\x12&\n\x1e\x61uthor_playtime_last_two_weeks\x18\x14 \x01(\x05\x12!\n\x19\x61uthor_playtime_at_review\x18\x15 \x01(\x05\x12\x1a\n\x12\x61uthor_last_played\x18\x16 \x01(\x05\"5\n\x13ListReviewsResponse\x12\x1e\n\x07reviews\x18\x01 \x03(\x0b\x32\r.ReviewObject\"(\n\x12ListReviewsRequest\x12\x12\n\nmaxResults\x18\x01 \x01(\x05\"9\n\x10GetReviewRequest\x12\x11\n\treview_id\x18\x01 \x01(\x05\x12\x12\n\nmaxResults\x18\x02 \x01(\x05\x32\xff\x01\n\x07Reviews\x12-\n\tGetReview\x12\x11.GetReviewRequest\x1a\r.ReviewObject\x12)\n\tAddReview\x12\r.ReviewObject\x1a\r.ReviewObject\x12,\n\x0cUpdateReview\x12\r.ReviewObject\x1a\r.ReviewObject\x12\x32\n\x0c\x44\x65leteReview\x12\x11.GetReviewRequest\x1a\x0f.SimpleResponse\x12\x38\n\x0bListReviews\x12\x13.ListReviewsRequest\x1a\x14.ListReviewsResponseb\x06proto3')



_REVIEWOBJECT = DESCRIPTOR.message_types_by_name['ReviewObject']
_LISTREVIEWSRESPONSE = DESCRIPTOR.message_types_by_name['ListReviewsResponse']
_LISTREVIEWSREQUEST = DESCRIPTOR.message_types_by_name['ListReviewsRequest']
_GETREVIEWREQUEST = DESCRIPTOR.message_types_by_name['GetReviewRequest']
ReviewObject = _reflection.GeneratedProtocolMessageType('ReviewObject', (_message.Message,), {
  'DESCRIPTOR' : _REVIEWOBJECT,
  '__module__' : 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:ReviewObject)
  })
_sym_db.RegisterMessage(ReviewObject)

ListReviewsResponse = _reflection.GeneratedProtocolMessageType('ListReviewsResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTREVIEWSRESPONSE,
  '__module__' : 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:ListReviewsResponse)
  })
_sym_db.RegisterMessage(ListReviewsResponse)

ListReviewsRequest = _reflection.GeneratedProtocolMessageType('ListReviewsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTREVIEWSREQUEST,
  '__module__' : 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:ListReviewsRequest)
  })
_sym_db.RegisterMessage(ListReviewsRequest)

GetReviewRequest = _reflection.GeneratedProtocolMessageType('GetReviewRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETREVIEWREQUEST,
  '__module__' : 'reviews_pb2'
  # @@protoc_insertion_point(class_scope:GetReviewRequest)
  })
_sym_db.RegisterMessage(GetReviewRequest)

_REVIEWS = DESCRIPTOR.services_by_name['Reviews']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REVIEWOBJECT._serialized_start=30
  _REVIEWOBJECT._serialized_end=610
  _LISTREVIEWSRESPONSE._serialized_start=612
  _LISTREVIEWSRESPONSE._serialized_end=665
  _LISTREVIEWSREQUEST._serialized_start=667
  _LISTREVIEWSREQUEST._serialized_end=707
  _GETREVIEWREQUEST._serialized_start=709
  _GETREVIEWREQUEST._serialized_end=766
  _REVIEWS._serialized_start=769
  _REVIEWS._serialized_end=1024
# @@protoc_insertion_point(module_scope)
