apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB1
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole1
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB2
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole2
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB3
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole3
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB4
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole4
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB5
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole5
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB6
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole6
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB7
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole7
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB8
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole8
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB9
  namespace: library
subjects:
  - kind: User
    name: libraryTeam9
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole9
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB10
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole10
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB11
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole11
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: libraryTeamRoleB12
  namespace: library
subjects:
  - kind: User
    name: libraryTeam
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: libraryTeamRole12
  apiGroup: rbac.authorization.k8s.io
