# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wishlist.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ewishlist.proto\"\xb5\x03\n\x04Game\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05types\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x65sc_snippet\x18\x04 \x01(\t\x12\x16\n\x0erecent_reviews\x18\x05 \x01(\t\x12\x13\n\x0b\x61ll_reviews\x18\x06 \x01(\t\x12\x14\n\x0crelease_date\x18\x07 \x01(\t\x12\x11\n\tdeveloper\x18\x08 \x01(\t\x12\x11\n\tpublisher\x18\t \x01(\t\x12\x14\n\x0cpopular_tags\x18\n \x01(\t\x12\x14\n\x0cgame_details\x18\x0b \x01(\t\x12\x11\n\tlanguages\x18\x0c \x01(\t\x12\x14\n\x0c\x61\x63hievements\x18\r \x01(\t\x12\r\n\x05genre\x18\x0e \x01(\t\x12\x18\n\x10game_description\x18\x0f \x01(\t\x12\x16\n\x0emature_content\x18\x10 \x01(\t\x12\x1c\n\x14minimum_requirements\x18\x11 \x01(\t\x12 \n\x18recommended_requirements\x18\x12 \x01(\t\x12\x16\n\x0eoriginal_price\x18\x13 \x01(\t\x12\x16\n\x0e\x64iscount_price\x18\x14 \x01(\t\"-\n\x15ListGamesWishResponse\x12\x14\n\x05games\x18\x01 \x03(\x0b\x32\x05.Game\"D\n\x14ListGamesWishRequest\x12\x13\n\x0bpage_number\x18\x01 \x01(\x05\x12\x17\n\x0fresult_per_page\x18\x02 \x01(\x05\"&\n\x13\x41\x64\x64GameWishResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"$\n\x15\x44\x65leteGameWishRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\")\n\x16\x44\x65leteGameWishResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xad\x01\n\x08Wishlist\x12:\n\tListGames\x12\x15.ListGamesWishRequest\x1a\x16.ListGamesWishResponse\x12&\n\x07\x41\x64\x64Game\x12\x05.Game\x1a\x14.AddGameWishResponse\x12=\n\nDeleteGame\x12\x16.DeleteGameWishRequest\x1a\x17.DeleteGameWishResponseb\x06proto3')



_GAME = DESCRIPTOR.message_types_by_name['Game']
_LISTGAMESWISHRESPONSE = DESCRIPTOR.message_types_by_name['ListGamesWishResponse']
_LISTGAMESWISHREQUEST = DESCRIPTOR.message_types_by_name['ListGamesWishRequest']
_ADDGAMEWISHRESPONSE = DESCRIPTOR.message_types_by_name['AddGameWishResponse']
_DELETEGAMEWISHREQUEST = DESCRIPTOR.message_types_by_name['DeleteGameWishRequest']
_DELETEGAMEWISHRESPONSE = DESCRIPTOR.message_types_by_name['DeleteGameWishResponse']
Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {
  'DESCRIPTOR' : _GAME,
  '__module__' : 'wishlist_pb2'
  # @@protoc_insertion_point(class_scope:Game)
  })
_sym_db.RegisterMessage(Game)

ListGamesWishResponse = _reflection.GeneratedProtocolMessageType('ListGamesWishResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTGAMESWISHRESPONSE,
  '__module__' : 'wishlist_pb2'
  # @@protoc_insertion_point(class_scope:ListGamesWishResponse)
  })
_sym_db.RegisterMessage(ListGamesWishResponse)

ListGamesWishRequest = _reflection.GeneratedProtocolMessageType('ListGamesWishRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTGAMESWISHREQUEST,
  '__module__' : 'wishlist_pb2'
  # @@protoc_insertion_point(class_scope:ListGamesWishRequest)
  })
_sym_db.RegisterMessage(ListGamesWishRequest)

AddGameWishResponse = _reflection.GeneratedProtocolMessageType('AddGameWishResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDGAMEWISHRESPONSE,
  '__module__' : 'wishlist_pb2'
  # @@protoc_insertion_point(class_scope:AddGameWishResponse)
  })
_sym_db.RegisterMessage(AddGameWishResponse)

DeleteGameWishRequest = _reflection.GeneratedProtocolMessageType('DeleteGameWishRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEGAMEWISHREQUEST,
  '__module__' : 'wishlist_pb2'
  # @@protoc_insertion_point(class_scope:DeleteGameWishRequest)
  })
_sym_db.RegisterMessage(DeleteGameWishRequest)

DeleteGameWishResponse = _reflection.GeneratedProtocolMessageType('DeleteGameWishResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEGAMEWISHRESPONSE,
  '__module__' : 'wishlist_pb2'
  # @@protoc_insertion_point(class_scope:DeleteGameWishResponse)
  })
_sym_db.RegisterMessage(DeleteGameWishResponse)

_WISHLIST = DESCRIPTOR.services_by_name['Wishlist']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAME._serialized_start=19
  _GAME._serialized_end=456
  _LISTGAMESWISHRESPONSE._serialized_start=458
  _LISTGAMESWISHRESPONSE._serialized_end=503
  _LISTGAMESWISHREQUEST._serialized_start=505
  _LISTGAMESWISHREQUEST._serialized_end=573
  _ADDGAMEWISHRESPONSE._serialized_start=575
  _ADDGAMEWISHRESPONSE._serialized_end=613
  _DELETEGAMEWISHREQUEST._serialized_start=615
  _DELETEGAMEWISHREQUEST._serialized_end=651
  _DELETEGAMEWISHRESPONSE._serialized_start=653
  _DELETEGAMEWISHRESPONSE._serialized_end=694
  _WISHLIST._serialized_start=697
  _WISHLIST._serialized_end=870
# @@protoc_insertion_point(module_scope)
