# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import userManagement_pb2 as userManagement__pb2


class UserManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddUser = channel.unary_unary(
                '/UserManagement/AddUser',
                request_serializer=userManagement__pb2.AddUserRequest.SerializeToString,
                response_deserializer=userManagement__pb2.DefaultResponse.FromString,
                )
        self.EditUser = channel.unary_unary(
                '/UserManagement/EditUser',
                request_serializer=userManagement__pb2.EditUserRequest.SerializeToString,
                response_deserializer=userManagement__pb2.DefaultResponse.FromString,
                )
        self.LoginUser = channel.unary_unary(
                '/UserManagement/LoginUser',
                request_serializer=userManagement__pb2.LoginRequest.SerializeToString,
                response_deserializer=userManagement__pb2.DefaultResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/UserManagement/Logout',
                request_serializer=userManagement__pb2.LogoutRequest.SerializeToString,
                response_deserializer=userManagement__pb2.DefaultResponse.FromString,
                )


class UserManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUser,
                    request_deserializer=userManagement__pb2.AddUserRequest.FromString,
                    response_serializer=userManagement__pb2.DefaultResponse.SerializeToString,
            ),
            'EditUser': grpc.unary_unary_rpc_method_handler(
                    servicer.EditUser,
                    request_deserializer=userManagement__pb2.EditUserRequest.FromString,
                    response_serializer=userManagement__pb2.DefaultResponse.SerializeToString,
            ),
            'LoginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginUser,
                    request_deserializer=userManagement__pb2.LoginRequest.FromString,
                    response_serializer=userManagement__pb2.DefaultResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=userManagement__pb2.LogoutRequest.FromString,
                    response_serializer=userManagement__pb2.DefaultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UserManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserManagement/AddUser',
            userManagement__pb2.AddUserRequest.SerializeToString,
            userManagement__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserManagement/EditUser',
            userManagement__pb2.EditUserRequest.SerializeToString,
            userManagement__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserManagement/LoginUser',
            userManagement__pb2.LoginRequest.SerializeToString,
            userManagement__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UserManagement/Logout',
            userManagement__pb2.LogoutRequest.SerializeToString,
            userManagement__pb2.DefaultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
