# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adminOperations.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61\x64minOperations.proto\"\xbb\x03\n\nGameObject\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05types\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x65sc_snippet\x18\x04 \x01(\t\x12\x16\n\x0erecent_reviews\x18\x05 \x01(\t\x12\x13\n\x0b\x61ll_reviews\x18\x06 \x01(\t\x12\x14\n\x0crelease_date\x18\x07 \x01(\t\x12\x11\n\tdeveloper\x18\x08 \x01(\t\x12\x11\n\tpublisher\x18\t \x01(\t\x12\x14\n\x0cpopular_tags\x18\n \x01(\t\x12\x14\n\x0cgame_details\x18\x0b \x01(\t\x12\x11\n\tlanguages\x18\x0c \x01(\t\x12\x14\n\x0c\x61\x63hievements\x18\r \x01(\x05\x12\r\n\x05genre\x18\x0e \x01(\t\x12\x18\n\x10game_description\x18\x0f \x01(\t\x12\x16\n\x0emature_content\x18\x10 \x01(\t\x12\x1c\n\x14minimum_requirements\x18\x11 \x01(\t\x12 \n\x18recommended_requirements\x18\x12 \x01(\t\x12\x16\n\x0eoriginal_price\x18\x13 \x01(\t\x12\x16\n\x0e\x64iscount_price\x18\x14 \x01(\t\"\"\n\x0f\x41\x64\x64GameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x12UpdateGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x11\x44\x65leteGameRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"%\n\x12\x44\x65leteGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd9\x01\n\x0f\x41\x64minOperations\x12(\n\x07\x41\x64\x64Game\x12\x0b.GameObject\x1a\x10.AddGameResponse\x12.\n\nUpdateGame\x12\x0b.GameObject\x1a\x13.UpdateGameResponse\x12\x35\n\nDeleteGame\x12\x12.DeleteGameRequest\x1a\x13.DeleteGameResponse\x12\x35\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponseb\x06proto3')



_GAMEOBJECT = DESCRIPTOR.message_types_by_name['GameObject']
_ADDGAMERESPONSE = DESCRIPTOR.message_types_by_name['AddGameResponse']
_UPDATEGAMERESPONSE = DESCRIPTOR.message_types_by_name['UpdateGameResponse']
_DELETEGAMEREQUEST = DESCRIPTOR.message_types_by_name['DeleteGameRequest']
_DELETEGAMERESPONSE = DESCRIPTOR.message_types_by_name['DeleteGameResponse']
_DELETEUSERREQUEST = DESCRIPTOR.message_types_by_name['DeleteUserRequest']
_DELETEUSERRESPONSE = DESCRIPTOR.message_types_by_name['DeleteUserResponse']
GameObject = _reflection.GeneratedProtocolMessageType('GameObject', (_message.Message,), {
  'DESCRIPTOR' : _GAMEOBJECT,
  '__module__' : 'adminOperations_pb2'
  # @@protoc_insertion_point(class_scope:GameObject)
  })
_sym_db.RegisterMessage(GameObject)

AddGameResponse = _reflection.GeneratedProtocolMessageType('AddGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDGAMERESPONSE,
  '__module__' : 'adminOperations_pb2'
  # @@protoc_insertion_point(class_scope:AddGameResponse)
  })
_sym_db.RegisterMessage(AddGameResponse)

UpdateGameResponse = _reflection.GeneratedProtocolMessageType('UpdateGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEGAMERESPONSE,
  '__module__' : 'adminOperations_pb2'
  # @@protoc_insertion_point(class_scope:UpdateGameResponse)
  })
_sym_db.RegisterMessage(UpdateGameResponse)

DeleteGameRequest = _reflection.GeneratedProtocolMessageType('DeleteGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEGAMEREQUEST,
  '__module__' : 'adminOperations_pb2'
  # @@protoc_insertion_point(class_scope:DeleteGameRequest)
  })
_sym_db.RegisterMessage(DeleteGameRequest)

DeleteGameResponse = _reflection.GeneratedProtocolMessageType('DeleteGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEGAMERESPONSE,
  '__module__' : 'adminOperations_pb2'
  # @@protoc_insertion_point(class_scope:DeleteGameResponse)
  })
_sym_db.RegisterMessage(DeleteGameResponse)

DeleteUserRequest = _reflection.GeneratedProtocolMessageType('DeleteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERREQUEST,
  '__module__' : 'adminOperations_pb2'
  # @@protoc_insertion_point(class_scope:DeleteUserRequest)
  })
_sym_db.RegisterMessage(DeleteUserRequest)

DeleteUserResponse = _reflection.GeneratedProtocolMessageType('DeleteUserResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERRESPONSE,
  '__module__' : 'adminOperations_pb2'
  # @@protoc_insertion_point(class_scope:DeleteUserResponse)
  })
_sym_db.RegisterMessage(DeleteUserResponse)

_ADMINOPERATIONS = DESCRIPTOR.services_by_name['AdminOperations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GAMEOBJECT._serialized_start=26
  _GAMEOBJECT._serialized_end=469
  _ADDGAMERESPONSE._serialized_start=471
  _ADDGAMERESPONSE._serialized_end=505
  _UPDATEGAMERESPONSE._serialized_start=507
  _UPDATEGAMERESPONSE._serialized_end=544
  _DELETEGAMEREQUEST._serialized_start=546
  _DELETEGAMEREQUEST._serialized_end=578
  _DELETEGAMERESPONSE._serialized_start=580
  _DELETEGAMERESPONSE._serialized_end=617
  _DELETEUSERREQUEST._serialized_start=619
  _DELETEUSERREQUEST._serialized_end=650
  _DELETEUSERRESPONSE._serialized_start=652
  _DELETEUSERRESPONSE._serialized_end=689
  _ADMINOPERATIONS._serialized_start=692
  _ADMINOPERATIONS._serialized_end=909
# @@protoc_insertion_point(module_scope)
