# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import adminOperations_pb2 as adminOperations__pb2


class AdminOperationsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddGame = channel.unary_unary(
                '/AdminOperations/AddGame',
                request_serializer=adminOperations__pb2.Game.SerializeToString,
                response_deserializer=adminOperations__pb2.AddGameResponse.FromString,
                )
        self.UpdateGame = channel.unary_unary(
                '/AdminOperations/UpdateGame',
                request_serializer=adminOperations__pb2.Game.SerializeToString,
                response_deserializer=adminOperations__pb2.UpdateGameResponse.FromString,
                )
        self.DeleteGame = channel.unary_unary(
                '/AdminOperations/DeleteGame',
                request_serializer=adminOperations__pb2.DeleteGameRequest.SerializeToString,
                response_deserializer=adminOperations__pb2.DeleteGameResponse.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/AdminOperations/DeleteUser',
                request_serializer=adminOperations__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=adminOperations__pb2.DeleteUserResponse.FromString,
                )


class AdminOperationsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminOperationsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddGame': grpc.unary_unary_rpc_method_handler(
                    servicer.AddGame,
                    request_deserializer=adminOperations__pb2.Game.FromString,
                    response_serializer=adminOperations__pb2.AddGameResponse.SerializeToString,
            ),
            'UpdateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateGame,
                    request_deserializer=adminOperations__pb2.Game.FromString,
                    response_serializer=adminOperations__pb2.UpdateGameResponse.SerializeToString,
            ),
            'DeleteGame': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGame,
                    request_deserializer=adminOperations__pb2.DeleteGameRequest.FromString,
                    response_serializer=adminOperations__pb2.DeleteGameResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=adminOperations__pb2.DeleteUserRequest.FromString,
                    response_serializer=adminOperations__pb2.DeleteUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AdminOperations', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminOperations(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AdminOperations/AddGame',
            adminOperations__pb2.Game.SerializeToString,
            adminOperations__pb2.AddGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AdminOperations/UpdateGame',
            adminOperations__pb2.Game.SerializeToString,
            adminOperations__pb2.UpdateGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AdminOperations/DeleteGame',
            adminOperations__pb2.DeleteGameRequest.SerializeToString,
            adminOperations__pb2.DeleteGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AdminOperations/DeleteUser',
            adminOperations__pb2.DeleteUserRequest.SerializeToString,
            adminOperations__pb2.DeleteUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
