apiVersion: v1
kind: Namespace
metadata:
  name: adminoperations
---
apiVersion: v1
kind: Namespace
metadata:
  name: usermanagement
---
apiVersion: v1
kind: Namespace
metadata:
  name: reviews
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
