name: Build and Push to GCR

on:
  push

env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  REGISTRY_HOSTNAME: gcr.io

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: google-github-actions/setup-gcloud@v0
      with:
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GCR_KEY }}
    - run: |
        gcloud auth configure-docker
    - name: Build and Push Docker Images Microservices
      run: |
        
        git clone https://github.com/mdmourao/CloudProjectGroup7.git
        cd CloudProjectGroup7
        
        cd MicroServices

        cd adminOperations
        docker build . -f server/Dockerfile -t adminoperationsserver
        docker tag adminoperationsserver gcr.io/${{ secrets.PROJECT_ID }}/adminoperationsserver        
        docker push gcr.io/${{ secrets.PROJECT_ID }}/adminoperationsserver

        docker build . -f api/Dockerfile -t adminoperationsapi
        docker tag adminoperationsapi gcr.io/${{ secrets.PROJECT_ID }}/adminoperationsapi
        docker push gcr.io/${{ secrets.PROJECT_ID }}/adminoperationsapi

        cd ..

        cd userManagement
        docker build . -f server/Dockerfile -t usermanagementserver
        docker tag usermanagementserver gcr.io/${{ secrets.PROJECT_ID }}/usermanagementserver
        docker push gcr.io/${{ secrets.PROJECT_ID }}/usermanagementserver

        docker build . -f api/Dockerfile -t usermanagementapi
        docker tag usermanagementapi gcr.io/${{ secrets.PROJECT_ID }}/usermanagementapi
        docker push gcr.io/${{ secrets.PROJECT_ID }}/usermanagementapi

        cd ..

        cd library
        docker build . -f server/Dockerfile -t libraryserver
        docker tag libraryserver gcr.io/${{ secrets.PROJECT_ID }}/libraryserver
        docker push gcr.io/${{ secrets.PROJECT_ID }}/libraryserver

        docker build . -f api/Dockerfile -t libraryapi
        docker tag libraryapi gcr.io/${{ secrets.PROJECT_ID }}/libraryapi
        docker push gcr.io/${{ secrets.PROJECT_ID }}/libraryapi

        cd ..

        cd wishlist
        docker build . -f server/Dockerfile -t wishlistserver
        docker tag wishlistserver gcr.io/${{ secrets.PROJECT_ID }}/wishlistserver
        docker push gcr.io/${{ secrets.PROJECT_ID }}/wishlistserver

        docker build . -f api/Dockerfile -t wishlistapi
        docker tag wishlistapi gcr.io/${{ secrets.PROJECT_ID }}/wishlistapi
        docker push gcr.io/${{ secrets.PROJECT_ID }}/wishlistapi

        cd ..

        cd suggestions
        docker build . -f server/Dockerfile -t suggestionsserver
        docker tag suggestionsserver gcr.io/${{ secrets.PROJECT_ID }}/suggestionsserver
        docker push gcr.io/${{ secrets.PROJECT_ID }}/suggestionsserver

        docker build . -f api/Dockerfile -t suggestionsapi
        docker tag suggestionsapi gcr.io/${{ secrets.PROJECT_ID }}/suggestionsapi
        docker push gcr.io/${{ secrets.PROJECT_ID }}/suggestionsapi

        cd ..

        cd searches
        docker build . -f server/Dockerfile -t searchesserver
        docker tag searchesserver gcr.io/${{ secrets.PROJECT_ID }}/searchesserver
        docker push gcr.io/${{ secrets.PROJECT_ID }}/searchesserver

        docker build . -f api/Dockerfile -t searchesapi
        docker tag searchesapi gcr.io/${{ secrets.PROJECT_ID }}/searchesapi
        docker push gcr.io/${{ secrets.PROJECT_ID }}/searchesapi

        cd ..

        cd reviews
        docker build . -f server/Dockerfile -t gcr.io/${{ secrets.PROJECT_ID }}/reviews-server
        docker push gcr.io/${{ secrets.PROJECT_ID }}/reviews-server

        docker build . -f api/Dockerfile -t gcr.io/${{ secrets.PROJECT_ID }}/reviews-api
        docker push gcr.io/${{ secrets.PROJECT_ID }}/reviews-api

        cd ..
