# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import searches_pb2 as searches__pb2


class SearchesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchGames = channel.unary_unary(
                '/Searches/SearchGames',
                request_serializer=searches__pb2.SearchGamesRequest.SerializeToString,
                response_deserializer=searches__pb2.SearchGamesResponse.FromString,
                )
        self.SearchGameById = channel.unary_unary(
                '/Searches/SearchGameById',
                request_serializer=searches__pb2.SearchGameRequest.SerializeToString,
                response_deserializer=searches__pb2.SearchGameResponse.FromString,
                )
        self.SearchReviews = channel.unary_unary(
                '/Searches/SearchReviews',
                request_serializer=searches__pb2.SearchReviewsRequest.SerializeToString,
                response_deserializer=searches__pb2.SearchReviewsResponse.FromString,
                )
        self.SearchReviewById = channel.unary_unary(
                '/Searches/SearchReviewById',
                request_serializer=searches__pb2.SearchReviewRequest.SerializeToString,
                response_deserializer=searches__pb2.SearchReviewResponse.FromString,
                )


class SearchesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SearchGames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchGameById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchReviews(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchReviewById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchGames': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchGames,
                    request_deserializer=searches__pb2.SearchGamesRequest.FromString,
                    response_serializer=searches__pb2.SearchGamesResponse.SerializeToString,
            ),
            'SearchGameById': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchGameById,
                    request_deserializer=searches__pb2.SearchGameRequest.FromString,
                    response_serializer=searches__pb2.SearchGameResponse.SerializeToString,
            ),
            'SearchReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchReviews,
                    request_deserializer=searches__pb2.SearchReviewsRequest.FromString,
                    response_serializer=searches__pb2.SearchReviewsResponse.SerializeToString,
            ),
            'SearchReviewById': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchReviewById,
                    request_deserializer=searches__pb2.SearchReviewRequest.FromString,
                    response_serializer=searches__pb2.SearchReviewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Searches', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Searches(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchGames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Searches/SearchGames',
            searches__pb2.SearchGamesRequest.SerializeToString,
            searches__pb2.SearchGamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchGameById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Searches/SearchGameById',
            searches__pb2.SearchGameRequest.SerializeToString,
            searches__pb2.SearchGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Searches/SearchReviews',
            searches__pb2.SearchReviewsRequest.SerializeToString,
            searches__pb2.SearchReviewsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchReviewById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Searches/SearchReviewById',
            searches__pb2.SearchReviewRequest.SerializeToString,
            searches__pb2.SearchReviewResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
